### ISSUE TITLE
Rake beaker is failing due to json gem requiring Ruby '~> 2.0' on Debian debian-78-x64 box

### ISSUE THREAD

**Issue by ayashjorden** [fog/fog-dynect#13]
Hi,
I'm getting the following error when running `rake beaker`:
                json requires Ruby version ~> 2.0.

The issue is with the _fog_ gem installation, full trace:

```
Warning! PATH is not properly set up, '$USER_HOME/.rvm/gems/ruby-2.3.1/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.3.1'.
$USER_HOME/.rvm/rubies/ruby-2.0.0-p648/bin/ruby -I$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib:$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-support-3.5.0/lib $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/exe/rspec spec/acceptance --color
$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/beaker-rspec-5.6.0/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/specinfra-2.61.1/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Beaker::Hypervisor, found some vagrant boxes to create
Bringing machine 'debian-78-x64' up with 'virtualbox' provider...
==> debian-78-x64: Importing base box 'puppetlabs/debian-7.8-64-nocm'...
Progress: 10%Progress: 20%Progress: 30%Progress: 40%Progress: 50%Progress: 60%Progress: 70%Progress: 80%Progress: 90%==> debian-78-x64: Matching MAC address for NAT networking...
==> debian-78-x64: Checking if box 'puppetlabs/debian-7.8-64-nocm' is up to date...
==> debian-78-x64: Setting the name of the VM: defaultyml_debian-78-x64_1477758759012_41151
==> debian-78-x64: Fixed port collision for 22 => 2222. Now on port 2200.
==> debian-78-x64: Clearing any previously set network interfaces...
==> debian-78-x64: Preparing network interfaces based on configuration...
    debian-78-x64: Adapter 1: nat
    debian-78-x64: Adapter 2: hostonly
==> debian-78-x64: Forwarding ports...
    debian-78-x64: 22 (guest) => 2200 (host) (adapter 1)
==> debian-78-x64: Running 'pre-boot' VM customizations...
==> debian-78-x64: Booting VM...
==> debian-78-x64: Waiting for machine to boot. This may take a few minutes...
    debian-78-x64: SSH address: 127.0.0.1:2200
    debian-78-x64: SSH username: vagrant
    debian-78-x64: SSH auth method: private key
==> debian-78-x64: Machine booted and ready!
==> debian-78-x64: Checking for guest additions in VM...
==> debian-78-x64: Setting hostname...
==> debian-78-x64: Configuring and enabling network interfaces...
==> debian-78-x64: Mounting shared folders...
    debian-78-x64: /vagrant => $DEV_PATH/puppetlabs-dns/.vagrant/beaker_vagrant_files/default.yml
Disabling updates.puppetlabs.com by modifying hosts file to resolve updates to 127.0.0.1 on debian-78-x64
localhost $ scp $DEV_PATH/puppetlabs-dns debian-78-x64:/etc/puppet/modules {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "bundle", "spec", "tests", "log", ".svn", "junit", "pkg", "example", ".", ".."]}
Destroying vagrant boxes
==> debian-78-x64: Forcing shutdown of VM...
==> debian-78-x64: Destroying VM and associated drives...

Finished in 3 minutes 10.3 seconds (files took 1 minute 32.03 seconds to load)
0 examples, 0 failures

$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/beaker-2.50.0/lib/beaker/host.rb:351:in `exec': Host 'debian-78-x64' exited with 1 running: (Beaker::Host::CommandFailure)
 gem install fog --no-ri --no-rdoc
Last 10 lines of output were:
        Building native extensions.  This could take a while...
        ERROR:  Error installing fog:
                json requires Ruby version ~> 2.0.
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/beaker-2.50.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/beaker-2.50.0/lib/beaker/shared/host_manager.rb:127:in `run_block_on'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/beaker-2.50.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/beaker-2.50.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
        from $DEV_PATH/puppetlabs-dns/spec/spec_helper_acceptance.rb:17:in `block (3 levels) in <top (required)>'
        from $DEV_PATH/puppetlabs-dns/spec/spec_helper_acceptance.rb:12:in `each'
        from $DEV_PATH/puppetlabs-dns/spec/spec_helper_acceptance.rb:12:in `block (2 levels) in <top (required)>'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/example.rb:443:in `instance_exec'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/example.rb:443:in `instance_exec'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/hooks.rb:350:in `run'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1879:in `block in run_hooks_with'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1879:in `each'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1879:in `run_hooks_with'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1835:in `with_suite_hooks'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:112:in `block in run_specs'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/reporter.rb:77:in `report'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:111:in `run_specs'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:87:in `run'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
        from $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/exe/rspec:4:in `<main>'
$USER_HOME/.rvm/rubies/ruby-2.0.0-p648/bin/ruby -I$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/lib:$DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-support-3.5.0/lib $DEV_PATH/puppetlabs-dns/vendor/gems/ruby/2.0.0/gems/rspec-core-3.5.2/exe/rspec spec/acceptance --color failed
```

We have the _fog_ gem installed on Ubuntu Wily 15.10,  maybe the issue is with the debian image in use?

Thank you,
Yarden

**Comment by plribeiro3000** [comment]
Which ruby version are you using?

Sorry for the long time to answer.

**Comment by ayashjorden** [comment]
Tried with both 2.0.0-p648 and 2.3.1

**Comment by plribeiro3000** [comment]
Hey. Sorry for the delay again. 
Is just did a little dig and the issue is not related to fog. The issue is the gem `beaker` because its latest version depends on `ruby >= 2.2.5` and `json ~> 1.8`.
And for whatever reason it seems you are installing the latest `json` version which depends on `ruby ~> 2.0` so you have a conflict.

Which version of bundler are you using?
Did you try to bum `beaker` version to the latest?

Links:
https://rubygems.org/gems/beaker
https://rubygems.org/gems/json
